//! C99 backend. Output is plain, readable C that gcc/clang/tcc can compile.

use std::fmt::Write;

use crate::ast::*;

const PRELUDE: &str = r#"// generated by nyra
#include <stdarg.h>
#include <float.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static void ny_print_int(int64_t x) { printf("%lld\n", (long long)x); }
static void ny_print_bool(bool x) { puts(x ? "true" : "false"); }
static void ny_print_str(const char *x) { puts(x); }
// Formats a float exactly like JavaScript's String(x): the shortest digits that
// round-trip, laid out by the ECMAScript Number::toString rules. buf needs 32 bytes.
static char *ny_float_fmt(char *buf, double x) {
    if (x != x) { strcpy(buf, "NaN"); return buf; }
    if (x == 0) { strcpy(buf, "0"); return buf; }
    if (x > DBL_MAX) { strcpy(buf, "Infinity"); return buf; }
    if (x < -DBL_MAX) { strcpy(buf, "-Infinity"); return buf; }
    char *out = buf;
    if (x < 0) { *out++ = '-'; x = -x; }
    char tmp[40];
    for (int p = 1; p <= 17; p++) {
        snprintf(tmp, sizeof tmp, "%.*e", p - 1, x);
        if (strtod(tmp, NULL) == x) break;
    }
    char digits[20];
    int k = 0;
    char *s = tmp;
    for (; *s && *s != 'e'; s++) if (*s >= '0' && *s <= '9') digits[k++] = *s;
    while (k > 1 && digits[k - 1] == '0') k--;
    int n = atoi(s + 1) + 1; // the value is 0.DIGITS * 10^n
    if (k <= n && n <= 21) {
        memcpy(out, digits, k); out += k;
        for (int i = k; i < n; i++) *out++ = '0';
    } else if (0 < n && n <= 21) {
        memcpy(out, digits, n); out += n; *out++ = '.';
        memcpy(out, digits + n, k - n); out += k - n;
    } else if (-6 < n && n <= 0) {
        *out++ = '0'; *out++ = '.';
        for (int i = n; i < 0; i++) *out++ = '0';
        memcpy(out, digits, k); out += k;
    } else {
        *out++ = digits[0];
        if (k > 1) { *out++ = '.'; memcpy(out, digits + 1, k - 1); out += k - 1; }
        out += sprintf(out, "e%c%d", n > 0 ? '+' : '-', n > 0 ? n - 1 : 1 - n);
    }
    *out = '\0';
    return buf;
}
static void ny_print_float(double x) { char buf[32]; puts(ny_float_fmt(buf, x)); }
// Builds an interpolated string. Not freed yet (the v0.3 memory model will).
static const char *ny_fmt(const char *fmt, ...) {
    va_list ap;
    va_start(ap, fmt);
    int n = vsnprintf(NULL, 0, fmt, ap);
    va_end(ap);
    char *s = malloc((size_t)n + 1);
    if (!s) { fputs("nyra: out of memory\n", stderr); exit(1); }
    va_start(ap, fmt);
    vsnprintf(s, (size_t)n + 1, fmt, ap);
    va_end(ap);
    return s;
}

"#;

const RESERVED: &[&str] = &[
    "auto", "break", "case", "char", "const", "continue", "default", "do", "double", "else", "enum",
    "extern", "float", "for", "goto", "if", "inline", "int", "long", "register", "restrict", "return",
    "short", "signed", "sizeof", "static", "struct", "switch", "typedef", "union", "unsigned", "void",
    "volatile", "while", "bool", "true", "false", "NULL", "EOF", "errno", "stdin", "stdout", "stderr",
    "main", "printf", "puts", "snprintf", "sprintf", "strcmp", "strcpy", "strtod", "memcpy", "atoi", "malloc",
    "exit", "int64_t", "DBL_MAX",
];

fn var(name: &str) -> String {
    if RESERVED.contains(&name) || name.starts_with("ny_") {
        format!("{name}_")
    } else {
        name.to_string()
    }
}

fn ctype(t: Type) -> &'static str {
    match t {
        Type::Int => "int64_t",
        Type::Float => "double",
        Type::Bool => "bool",
        Type::Str => "const char*",
        Type::Void | Type::Unknown => "void",
    }
}

fn signature(f: &Func) -> String {
    let params = if f.params.is_empty() {
        "void".to_string()
    } else {
        f.params.iter().map(|p| format!("{} {}", ctype(p.ty), var(&p.name))).collect::<Vec<_>>().join(", ")
    };
    format!("static {} ny_{}({})", ctype(f.ret), f.name, params)
}

pub fn gen(prog: &Program) -> String {
    let mut g = Gen { out: String::from(PRELUDE), indent: 0, tmp: 0 };
    for f in &prog.funcs {
        let _ = writeln!(g.out, "{};", signature(f));
    }
    g.out.push('\n');
    for f in &prog.funcs {
        g.line(&format!("{} {{", signature(f)));
        g.block(&f.body);
        g.line("}");
        g.out.push('\n');
    }
    g.out.push_str("int main(void) {\n    ny_main();\n    return 0;\n}\n");
    g.out
}

struct Gen {
    out: String,
    indent: usize,
    tmp: usize,
}

impl Gen {
    fn line(&mut self, s: &str) {
        for _ in 0..self.indent {
            self.out.push_str("    ");
        }
        self.out.push_str(s);
        self.out.push('\n');
    }

    fn block(&mut self, b: &[Stmt]) {
        self.indent += 1;
        for s in b {
            self.stmt(s);
        }
        self.indent -= 1;
    }

    fn stmt(&mut self, s: &Stmt) {
        match &s.kind {
            StmtKind::Let { name, ty, value, .. } => {
                let t = ty.unwrap_or(value.ty);
                self.line(&format!("{} {} = {};", ctype(t), var(name), expr(value)));
            }
            StmtKind::Assign { name, value } => self.line(&format!("{} = {};", var(name), expr(value))),
            StmtKind::If { .. } => self.if_chain(s),
            StmtKind::While { cond, body } => {
                self.line(&format!("while ({}) {{", expr(cond)));
                self.block(body);
                self.line("}");
            }
            StmtKind::For { var: v, start, end, body } => {
                self.tmp += 1;
                let (i, e) = (var(v), format!("ny_end{}", self.tmp));
                self.line(&format!(
                    "for (int64_t {i} = {}, {e} = {}; {i} < {e}; {i}++) {{",
                    expr(start),
                    expr(end)
                ));
                self.block(body);
                self.line("}");
            }
            StmtKind::Ret(None) => self.line("return;"),
            StmtKind::Ret(Some(e)) => self.line(&format!("return {};", expr(e))),
            StmtKind::Expr(e) => self.line(&format!("{};", expr(e))),
        }
    }

    fn if_chain(&mut self, s: &Stmt) {
        let mut cur = s;
        let mut first = true;
        loop {
            let StmtKind::If { cond, then, els } = &cur.kind else { unreachable!() };
            let head = if first { "if" } else { "} else if" };
            self.line(&format!("{head} ({}) {{", expr(cond)));
            first = false;
            self.block(then);
            match els {
                Some(e) if e.len() == 1 && matches!(e[0].kind, StmtKind::If { .. }) => cur = &e[0],
                Some(e) => {
                    self.line("} else {");
                    self.block(e);
                    self.line("}");
                    return;
                }
                None => {
                    self.line("}");
                    return;
                }
            }
        }
    }
}

fn expr(e: &Expr) -> String {
    match &e.kind {
        ExprKind::Int(n) => {
            if *n > i32::MAX as i64 || *n < i32::MIN as i64 {
                format!("INT64_C({n})")
            } else {
                n.to_string()
            }
        }
        ExprKind::Float(f) => format!("{f:?}"),
        ExprKind::Bool(b) => b.to_string(),
        ExprKind::Str(s) => string_lit(s),
        ExprKind::Interp(parts) => {
            let (fmt, args) = interp(parts);
            format!("ny_fmt({}{args})", string_lit(&fmt))
        }
        ExprKind::Var(n) => var(n),
        ExprKind::Unary(op, x) => format!("({}{})", if *op == UnOp::Neg { "-" } else { "!" }, expr(x)),
        ExprKind::If(c, a, b) => format!("({} ? {} : {})", expr(c), expr(a), expr(b)),
        ExprKind::Binary(op, l, r) => {
            if l.ty == Type::Str && matches!(op, BinOp::Eq | BinOp::Ne) {
                format!("(strcmp({}, {}) {} 0)", expr(l), expr(r), op.symbol())
            } else {
                format!("({} {} {})", expr(l), op.symbol(), expr(r))
            }
        }
        ExprKind::Call(name, args) => {
            let a: Vec<String> = args.iter().map(expr).collect();
            match name.as_str() {
                "print" => match &args[0].kind {
                    // print("x = {x}") becomes a single printf, no allocation
                    ExprKind::Interp(parts) => {
                        let (fmt, args) = interp(parts);
                        format!("printf({}{args})", string_lit(&(fmt + "\n")))
                    }
                    _ => format!("ny_print_{}({})", args[0].ty.name(), a[0]),
                },
                "int" => format!("((int64_t)({}))", a[0]),
                "float" => format!("((double)({}))", a[0]),
                _ => format!("ny_{}({})", name, a.join(", ")),
            }
        }
    }
}

/// printf-style format string and the matching argument list (", a, b") for an interpolated string.
fn interp(parts: &[InterpPart]) -> (String, String) {
    let mut fmt = String::new();
    let mut args = String::new();
    for p in parts {
        match p {
            InterpPart::Lit(s) => fmt.push_str(&s.replace('%', "%%")),
            InterpPart::Expr(e) => {
                let x = expr(e);
                let (spec, arg) = match e.ty {
                    Type::Int => ("%lld", format!("(long long)({x})")),
                    Type::Float => ("%s", format!("ny_float_fmt((char[32]){{0}}, {x})")),
                    Type::Bool => ("%s", format!("(({x}) ? \"true\" : \"false\")")),
                    _ => ("%s", x),
                };
                fmt.push_str(spec);
                args.push_str(", ");
                args.push_str(&arg);
            }
        }
    }
    (fmt, args)
}

fn string_lit(s: &str) -> String {
    let mut out = String::from("\"");
    for b in s.bytes() {
        match b {
            b'"' => out.push_str("\\\""),
            b'\\' => out.push_str("\\\\"),
            b'\n' => out.push_str("\\n"),
            b'\t' => out.push_str("\\t"),
            b'\r' => out.push_str("\\r"),
            b'?' => out.push_str("\\?"),
            0x20..=0x7e => out.push(b as char),
            _ => {
                let _ = write!(out, "\\{b:03o}");
            }
        }
    }
    out.push('"');
    out
}
