//! JavaScript backend. Output runs on Node.js or in the browser.

use std::fmt::Write;

use super::{bare, names};
use crate::ir::{BinOp, Expr, Func, LocalId, Module, RtOp, Stmt, StmtKind, Ty, UnOp};

const RESERVED: &[&str] = &[
    "arguments", "await", "break", "case", "catch", "class", "const", "continue", "debugger", "default",
    "delete", "do", "else", "enum", "eval", "export", "extends", "false", "finally", "for", "function",
    "if", "implements", "import", "in", "instanceof", "interface", "let", "new", "null", "package",
    "private", "protected", "public", "return", "static", "super", "switch", "this", "throw", "true",
    "try", "typeof", "var", "void", "while", "with", "yield", "undefined", "NaN", "Infinity", "console",
    "Math", "String", "Number", "Object", "Array", "JSON", "Symbol", "BigInt", "Error", "globalThis",
    "process", "require", "module", "exports", "NyPanic",
];

const PRELUDE: &str = r#"// generated by nyra
"use strict";

const ny_file = @FILE@;

// Runtime errors: same text as the C backend; the entry point prints it and exits with 101.
class NyPanic extends Error {}
function ny_panic(code, msg, hint, line, col) {
    const json = typeof process !== "undefined" && process.env.NYRA_JSON;
    const text = json
        ? JSON.stringify({ ok: false, errors: [{ code, message: msg, file: ny_file, line, col, hint, runtime: true }] })
        : `runtime error[${code}]: ${msg}\n  --> ${ny_file}:${line}:${col}\n  = hint: ${hint}`;
    throw new NyPanic(text);
}
// int / and %: division by zero is a runtime error; `+ 0` avoids -0.
function ny_div(a, b, line, col) {
    if (b === 0) ny_panic("E0241", "division by zero", "check the divisor first", line, col);
    return Math.trunc(a / b) + 0;
}
function ny_mod(a, b, line, col) {
    if (b === 0) ny_panic("E0241", "division by zero", "check the divisor first", line, col);
    return (a % b) + 0;
}
// int(x) of a float: truncates toward zero; NaN or a value outside the int range is an error.
function ny_f2i(x, line, col) {
    if (Number.isNaN(x) || x >= 9223372036854775807 || x < -9223372036854775808) {
        ny_panic("E0245", "cannot convert " + String(x) + " to int",
            "int(x) needs a float that is not NaN and fits in an int", line, col);
    }
    return Math.trunc(x) + 0;
}

"#;

fn name(n: &str) -> String {
    if RESERVED.contains(&n) || n.starts_with("ny_") {
        format!("{n}_")
    } else {
        n.to_string()
    }
}

/// `file` is the source path as given to nyra; runtime errors report it.
pub fn gen(m: &Module, file: &str) -> String {
    let mut out = PRELUDE.replace("@FILE@", &crate::diag::json_str(file));
    for f in &m.funcs {
        let n = names::locals(f, name, "ny_");
        let _ = writeln!(out, "function {}({}) {{", name(&f.name), n[..f.params].join(", "));
        // every local is declared at the top; statements only assign
        if f.locals.len() > f.params {
            let _ = writeln!(out, "    let {};", n[f.params..].join(", "));
        }
        let mut g = Gen { m, f, names: &n, out: String::new(), indent: 1 };
        g.stmts(&f.body);
        out.push_str(&g.out);
        out.push_str("}\n\n");
    }
    let _ = write!(
        out,
        concat!(
            "try {{\n",
            "    {}();\n",
            "}} catch (e) {{\n",
            "    if (!(e instanceof NyPanic)) throw e;\n",
            "    console.error(e.message);\n",
            "    // exitCode instead of process.exit(), so buffered stdout is never cut off\n",
            "    if (typeof process !== \"undefined\") process.exitCode = 101;\n",
            "}}\n",
        ),
        name(&m.func(m.main).name)
    );
    out
}

struct Gen<'a> {
    m: &'a Module,
    f: &'a Func,
    names: &'a [String],
    out: String,
    indent: usize,
}

impl Gen<'_> {
    fn line(&mut self, s: &str) {
        for _ in 0..self.indent {
            self.out.push_str("    ");
        }
        self.out.push_str(s);
        self.out.push('\n');
    }

    fn block(&mut self, ss: &[Stmt]) {
        self.indent += 1;
        self.stmts(ss);
        self.indent -= 1;
    }

    fn stmts(&mut self, ss: &[Stmt]) {
        for s in ss {
            self.stmt(s);
        }
    }

    fn local(&self, l: LocalId) -> &str {
        &self.names[l.0 as usize]
    }

    /// `dst = value;` or `value;`
    fn assign(&self, dst: Option<LocalId>, value: String) -> String {
        match dst {
            Some(d) => format!("{} = {value};", self.local(d)),
            None => format!("{value};"),
        }
    }

    fn stmt(&mut self, s: &Stmt) {
        let at = format!("{}, {}", s.span.line, s.span.col);
        match &s.kind {
            StmtKind::Set(l, e) => {
                let line = format!("{} = {};", self.local(*l), bare(&self.expr(e)));
                self.line(&line);
            }
            StmtKind::Call { dst, func, args } => {
                let args: Vec<String> = args.iter().map(|a| bare(&self.expr(a)).to_string()).collect();
                let line = self.assign(*dst, format!("{}({})", name(&self.m.func(*func).name), args.join(", ")));
                self.line(&line);
            }
            StmtKind::Op { dst, op, args } => {
                let code = match op {
                    RtOp::Print => self.print(args),
                    RtOp::Format => self.template(args),
                    RtOp::DivInt => format!("ny_div({}, {}, {at})", self.expr(&args[0]), self.expr(&args[1])),
                    RtOp::RemInt => format!("ny_mod({}, {}, {at})", self.expr(&args[0]), self.expr(&args[1])),
                    RtOp::FloatToInt => format!("ny_f2i({}, {at})", self.expr(&args[0])),
                };
                let line = self.assign(*dst, code);
                self.line(&line);
            }
            StmtKind::If { .. } => self.if_chain(s),
            StmtKind::Loop { head, cond, body, step } => self.lp(head, cond, body, step),
            StmtKind::Return(None) => self.line("return;"),
            StmtKind::Return(Some(e)) => {
                let line = format!("return {};", bare(&self.expr(e)));
                self.line(&line);
            }
        }
    }

    fn if_chain(&mut self, s: &Stmt) {
        let mut cur = s;
        let mut head = "if";
        loop {
            let StmtKind::If { cond, then, els } = &cur.kind else { unreachable!() };
            let line = format!("{head} ({}) {{", bare(&self.expr(cond)));
            self.line(&line);
            self.block(then);
            match els.as_slice() {
                [] => break,
                [next] if matches!(next.kind, StmtKind::If { .. }) => {
                    cur = next;
                    head = "} else if";
                }
                _ => {
                    self.line("} else {");
                    self.block(els);
                    break;
                }
            }
        }
        self.line("}");
    }

    fn lp(&mut self, head: &[Stmt], cond: &Expr, body: &[Stmt], step: &[Stmt]) {
        let full = self.expr(cond);
        let c = bare(&full);
        match (head, step) {
            ([], []) => {
                self.line(&format!("while ({c}) {{"));
                self.block(body);
            }
            ([], [Stmt { kind: StmtKind::Set(l, e), .. }]) => {
                let line = format!("for (; {c}; {} = {}) {{", self.local(*l), bare(&self.expr(e)));
                self.line(&line);
                self.block(body);
            }
            _ => {
                self.line("for (;;) {");
                self.indent += 1;
                self.stmts(head);
                self.line(&format!("if (!{full}) break;"));
                self.stmts(body);
                self.stmts(step);
                self.indent -= 1;
            }
        }
        self.line("}");
    }

    /// Numbers print through `String()` so `-0` shows as `0`, like the C backend.
    fn print(&self, parts: &[Expr]) -> String {
        if let [p] = parts {
            let x = self.expr(p);
            return match p.ty(self.f) {
                Ty::Int | Ty::Float => format!("console.log(String({x}))"),
                Ty::Bool | Ty::Str => format!("console.log({x})"),
            };
        }
        format!("console.log({})", self.template(parts))
    }

    /// A template literal for string parts: text is escaped, values become `${...}`.
    fn template(&self, parts: &[Expr]) -> String {
        let mut s = String::from("`");
        for p in parts {
            if let Expr::Str(id) = p {
                for c in self.m.str(*id).chars() {
                    match c {
                        '\\' => s.push_str("\\\\"),
                        '`' => s.push_str("\\`"),
                        '$' => s.push_str("\\$"),
                        '\n' => s.push_str("\\n"),
                        '\r' => s.push_str("\\r"),
                        '\t' => s.push_str("\\t"),
                        c if (c as u32) < 0x20 => s.push_str(&format!("\\u{:04x}", c as u32)),
                        c => s.push(c),
                    }
                }
                continue;
            }
            s.push_str("${");
            s.push_str(&self.expr(p));
            s.push('}');
        }
        s.push('`');
        s
    }

    fn expr(&self, e: &Expr) -> String {
        match e {
            Expr::Int(n) => n.to_string(),
            Expr::Float(f) => format!("{f:?}"),
            Expr::Bool(b) => b.to_string(),
            Expr::Str(id) => crate::diag::json_str(self.m.str(*id)),
            Expr::Local(l) => self.local(*l).to_string(),
            Expr::Unary(op, x) => {
                let x = self.expr(x);
                // never print `--x` (that would be a decrement)
                let neg = if x.starts_with('-') { format!("-({x})") } else { format!("-{x}") };
                match op {
                    // `+ 0` turns an int -0 into 0 (C has no -0 for ints)
                    UnOp::INeg => format!("({neg} + 0)"),
                    UnOp::FNeg => format!("({neg})"),
                    UnOp::Not => format!("(!{x})"),
                }
            }
            Expr::Binary(op, a, b) => {
                let (a, b) = (self.expr(a), self.expr(b));
                match op {
                    BinOp::IMul => format!("({a} * {b} + 0)"),
                    BinOp::IDiv => format!("(Math.trunc({a} / {b}) + 0)"),
                    BinOp::IRem => format!("({a} % {b} + 0)"),
                    BinOp::IEq | BinOp::FEq | BinOp::BEq | BinOp::SEq => format!("({a} === {b})"),
                    BinOp::INe | BinOp::FNe | BinOp::BNe | BinOp::SNe => format!("({a} !== {b})"),
                    _ => format!("({a} {} {b})", op.symbol()),
                }
            }
            Expr::Select(c, a, b) => format!("({} ? {} : {})", self.expr(c), self.expr(a), self.expr(b)),
            Expr::IntToFloat(x) => self.expr(x),
        }
    }
}
