//! JavaScript backend. Output runs on Node.js or in the browser.

use crate::ast::*;

const RESERVED: &[&str] = &[
    "arguments", "await", "break", "case", "catch", "class", "const", "continue", "debugger", "default",
    "delete", "do", "else", "enum", "eval", "export", "extends", "false", "finally", "for", "function",
    "if", "implements", "import", "in", "instanceof", "interface", "let", "new", "null", "package",
    "private", "protected", "public", "return", "static", "super", "switch", "this", "throw", "true",
    "try", "typeof", "var", "void", "while", "with", "yield", "undefined", "NaN", "Infinity", "console",
    "Math", "String", "Number", "Object", "Array", "JSON", "Symbol", "BigInt", "Error", "globalThis",
    "process", "require", "module", "exports",
];

const PRELUDE: &str = r#"// generated by nyra
"use strict";

// int(x): truncates toward zero; NaN gives 0 and out-of-range values saturate.
function ny_int(x) {
    if (Number.isNaN(x)) return 0;
    return Math.trunc(Math.min(Math.max(x, -9223372036854775808), 9223372036854775807)) + 0;
}

"#;

fn name(n: &str) -> String {
    if RESERVED.contains(&n) || n.starts_with("ny_") {
        format!("{n}_")
    } else {
        n.to_string()
    }
}

pub fn gen(prog: &Program) -> String {
    let mut g = Gen { out: String::from(PRELUDE), indent: 0, tmp: 0 };
    for f in &prog.funcs {
        let params: Vec<String> = f.params.iter().map(|p| name(&p.name)).collect();
        g.line(&format!("function {}({}) {{", name(&f.name), params.join(", ")));
        g.block(&f.body);
        g.line("}");
        g.out.push('\n');
    }
    g.out.push_str("main();\n");
    g.out
}

struct Gen {
    out: String,
    indent: usize,
    tmp: usize,
}

impl Gen {
    fn line(&mut self, s: &str) {
        for _ in 0..self.indent {
            self.out.push_str("    ");
        }
        self.out.push_str(s);
        self.out.push('\n');
    }

    fn block(&mut self, b: &[Stmt]) {
        self.indent += 1;
        for s in b {
            self.stmt(s);
        }
        self.indent -= 1;
    }

    fn stmt(&mut self, s: &Stmt) {
        match &s.kind {
            StmtKind::Let { name: n, mutable, value, .. } => {
                let kw = if *mutable { "let" } else { "const" };
                self.line(&format!("{kw} {} = {};", name(n), expr(value)));
            }
            StmtKind::Assign { name: n, value } => self.line(&format!("{} = {};", name(n), expr(value))),
            StmtKind::If { .. } => self.if_chain(s),
            StmtKind::While { cond, body } => {
                self.line(&format!("while ({}) {{", expr(cond)));
                self.block(body);
                self.line("}");
            }
            StmtKind::For { var, start, end, body } => {
                self.tmp += 1;
                let (i, e) = (name(var), format!("ny_end{}", self.tmp));
                self.line(&format!("for (let {i} = {}, {e} = {}; {i} < {e}; {i}++) {{", expr(start), expr(end)));
                self.block(body);
                self.line("}");
            }
            StmtKind::Ret(None) => self.line("return;"),
            StmtKind::Ret(Some(e)) => self.line(&format!("return {};", expr(e))),
            StmtKind::Expr(e) => self.line(&format!("{};", expr(e))),
        }
    }

    fn if_chain(&mut self, s: &Stmt) {
        let mut cur = s;
        let mut first = true;
        loop {
            let StmtKind::If { cond, then, els } = &cur.kind else { unreachable!() };
            let head = if first { "if" } else { "} else if" };
            self.line(&format!("{head} ({}) {{", expr(cond)));
            first = false;
            self.block(then);
            match els {
                Some(e) if e.len() == 1 && matches!(e[0].kind, StmtKind::If { .. }) => cur = &e[0],
                Some(e) => {
                    self.line("} else {");
                    self.block(e);
                    self.line("}");
                    return;
                }
                None => {
                    self.line("}");
                    return;
                }
            }
        }
    }
}

fn expr(e: &Expr) -> String {
    match &e.kind {
        ExprKind::Int(n) => n.to_string(),
        ExprKind::Float(f) => format!("{f:?}"),
        ExprKind::Bool(b) => b.to_string(),
        ExprKind::Str(s) => crate::diag::json_str(s),
        ExprKind::Interp(parts) => {
            let mut s = String::from("`");
            for p in parts {
                match p {
                    InterpPart::Lit(t) => {
                        for c in t.chars() {
                            match c {
                                '\\' => s.push_str("\\\\"),
                                '`' => s.push_str("\\`"),
                                '$' => s.push_str("\\$"),
                                '\n' => s.push_str("\\n"),
                                '\r' => s.push_str("\\r"),
                                '\t' => s.push_str("\\t"),
                                c if (c as u32) < 0x20 => s.push_str(&format!("\\u{:04x}", c as u32)),
                                c => s.push(c),
                            }
                        }
                    }
                    InterpPart::Expr(e) => {
                        s.push_str("${");
                        s.push_str(&expr(e));
                        s.push('}');
                    }
                }
            }
            s.push('`');
            s
        }
        ExprKind::Var(n) => name(n),
        // `+ 0` turns an int -0 into 0 (C has no -0 for ints)
        ExprKind::Unary(UnOp::Neg, x) if e.ty == Type::Int => format!("(-{} + 0)", expr(x)),
        ExprKind::Unary(op, x) => format!("({}{})", if *op == UnOp::Neg { "-" } else { "!" }, expr(x)),
        ExprKind::If(c, a, b) => format!("({} ? {} : {})", expr(c), expr(a), expr(b)),
        ExprKind::Binary(op, l, r) => {
            let (a, b) = (expr(l), expr(r));
            match op {
                BinOp::Div if e.ty == Type::Int => format!("(Math.trunc({a} / {b}) + 0)"),
                BinOp::Mul | BinOp::Mod if e.ty == Type::Int => format!("({a} {} {b} + 0)", op.symbol()),
                BinOp::Eq => format!("({a} === {b})"),
                BinOp::Ne => format!("({a} !== {b})"),
                _ => format!("({a} {} {b})", op.symbol()),
            }
        }
        ExprKind::Call(n, args) => {
            let a: Vec<String> = args.iter().map(expr).collect();
            match n.as_str() {
                // String() so that -0 prints as "0", like the C backend
                "print" => match args[0].ty {
                    Type::Int | Type::Float => format!("console.log(String({}))", a[0]),
                    _ => format!("console.log({})", a[0]),
                },
                "int" if args[0].ty == Type::Float => format!("ny_int({})", a[0]),
                "int" | "float" => a[0].clone(),
                _ => format!("{}({})", name(n), a.join(", ")),
            }
        }
    }
}
