// generated by nyra
"use strict";

const ny_file = @FILE@;

// Runtime errors: same text as the C backend; the entry point prints it and exits with 101.
class NyPanic extends Error {}
function ny_panic(code, msg, hint, line, col) {
    const json = typeof process !== "undefined" && process.env.NYRA_JSON;
    const text = json
        ? JSON.stringify({ ok: false, errors: [{ code, message: msg, file: ny_file, line, col, hint, runtime: true }] })
        : `runtime error[${code}]: ${msg}\n  --> ${ny_file}:${line}:${col}\n  = hint: ${hint}\n  = explain: nyra explain ${code}`;
    throw new NyPanic(text);
}
function ny_oom(line, col) {
    ny_panic("E0249", "out of memory", "the program needs more memory than the system gave it", line, col);
}
// What the entry point reports: a Nyra runtime error, or the engine running out of memory
// (E0249, without a position). Anything else is a bug in nyra and is thrown on.
function ny_rescue(e) {
    if (e instanceof NyPanic) return e;
    if (e instanceof RangeError && /invalid (string|array|typed array) length|allocation failed/i.test(e.message)) {
        try { ny_oom(0, 0); } catch (p) { return p; }
    }
    throw e;
}
// int / and %: division by zero is a runtime error; `+ 0` avoids -0.
function ny_div(a, b, line, col) {
    if (b === 0) ny_panic("E0241", "division by zero", "check the divisor first", line, col);
    return Math.trunc(a / b) + 0;
}
function ny_mod(a, b, line, col) {
    if (b === 0) ny_panic("E0241", "division by zero", "check the divisor first", line, col);
    return (a % b) + 0;
}
// `for i in a..b step k`: a step of 0 would never end.
function ny_check_step(k, line, col) {
    if (k === 0) ny_panic("E0243", "range step must not be 0", "use a positive step to count up and a negative one to count down", line, col);
}
// `xs.min()` / `xs.max()` of an empty array (`n` elements seen; `max` says which method).
function ny_check_non_empty(n, max, line, col) {
    if (n === 0) ny_panic("E0247", max ? "max() of an empty array" : "min() of an empty array", "an empty array has no smallest or largest element: check `xs.len() > 0` first, or start from a value of your own with `fold`", line, col);
}
// int(x) of a float: truncates toward zero; NaN or a value outside the int range is an error.
function ny_f2i(x, line, col) {
    if (Number.isNaN(x) || x >= 9223372036854775807 || x < -9223372036854775808) {
        ny_panic("E0245", "cannot convert " + String(x) + " to int",
            "int(x) needs a float that is not NaN and fits in an int", line, col);
    }
    return Math.trunc(x) + 0;
}

