"""Writes src/std/math.nyra (run: python tools/gen_std_math.py): fdlibm-style math in Nyra.
`K(...)` marks a constant written in exponent notation; it becomes a plain decimal literal
(Nyra has no exponent literals). The powers of two of `_pow2` and `_frexp` are written out too."""
import os
import re
from decimal import Decimal

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src", "std", "math.nyra")


def lit(v):
    """The shortest decimal that reads back as the double v, without an exponent."""
    s = format(Decimal(repr(float(v))), 'f')
    if '.' not in s:
        s += '.0'
    return s


def K(m):
    return lit(float(m.group(1)))


powers = [512, 256, 128, 64, 32, 16, 8, 4, 2, 1]
split_up = "\n".join(f"        if m >= {lit(2.0 ** s)} {{\n            m = m * {lit(2.0 ** -s)}\n            k += {s}\n        }}" for s in powers)
split_down = "\n".join(f"        if m * {lit(2.0 ** s)} < 2.0 {{\n            m = m * {lit(2.0 ** s)}\n            k -= {s}\n        }}" for s in powers)
pow2_pos = "\n".join(f"    if n >= {s} {{\n        r = r * {lit(2.0 ** s)}\n        n -= {s}\n    }}" for s in powers)
pow2_neg = "\n".join(f"    if n <= -{s} {{\n        r = r * {lit(2.0 ** -s)}\n        n += {s}\n    }}" for s in powers)

SRC = r'''// The math functions that every host computes a little differently (`exp`, `log`, `sin`, ...),
// written in Nyra so that every backend runs the same IEEE operations and prints the same
// digits (see stdlib.rs). They follow fdlibm (Sun's freely distributable libm, which JavaScript
// engines use too); `pow` uses double-double arithmetic. Helpers whose names start with `_` are
// private. Generated by tools/gen_std_math.py: change the script, not this file.

// |x|, with +0.0 for -0.0
fn _fabs(x: float) -> float = if x <= 0.0 { 0.0 - x } else { x }

// True for -0.0 and every negative number.
fn _neg(x: float) -> bool = x < 0.0 || (x == 0.0 && 1.0 / x < 0.0)

// 2^n exactly, for -1074 <= n <= 1023.
fn _pow2(k: int) -> float {
    var r = 1.0
    var n = k
@POW2POS@
@POW2NEG@
    ret r
}

// x with the low 32 bits of its encoding cleared (fdlibm's SET_LOW_WORD(x, 0)): 21 significant bits.
fn _cut(x: float) -> float {
    if x == 0.0 {
        ret x
    }
    var e = 0
    let m = _frexp(_fabs(x), inout e)
    let c = math.floor(m * 1048576.0) / 1048576.0 * _pow2(e)
    if x < 0.0 {
        ret -c
    }
    ret c
}

// y * 2^k with one rounding (fdlibm's scalbn for the results of exp).
fn _scale(y: float, k: int) -> float {
    if k > 1023 {
        ret y * _pow2(1023) * _pow2(k - 1023)
    }
    if k < -1022 {
        ret y * _pow2(k + 1000) * _pow2(-1000)
    }
    ret y * _pow2(k)
}

// x = m * 2^e with m in [1, 2), for a finite x > 0.
fn _frexp(x: float, inout e: int) -> float {
    var m = x
    var k = 0
    if m < K(2.2250738585072014e-308) {
        m = m * K(18014398509481984.0)
        k = -54
    }
    if m >= 2.0 {
@SPLITUP@
    } else if m < 1.0 {
@SPLITDOWN@
    }
    e = k
    ret m
}

// ---- exp ----

// e^(x + xl), xl a tiny correction (0 for exp itself). x is in [-745.2, 709.8].
fn _expk(x: float, xl: float) -> float {
    var k = 0
    var hi = x
    var lo = -xl
    let ax = _fabs(x)
    if ax >= K(0.3465735912322998) {
        if ax < K(1.0397205352783203) {
            if x == 1.0 && xl == 0.0 {
                ret K(2.718281828459045)
            }
            if x > 0.0 {
                hi = x - K(6.93147180369123816490e-01)
                lo = K(1.90821492927058770002e-10) - xl
                k = 1
            } else {
                hi = x + K(6.93147180369123816490e-01)
                lo = -K(1.90821492927058770002e-10) - xl
                k = -1
            }
        } else {
            k = int(K(1.44269504088896338700e+00) * x + (if x < 0.0 { -0.5 } else { 0.5 }))
            let t = float(k)
            hi = x - t * K(6.93147180369123816490e-01)
            lo = t * K(1.90821492927058770002e-10) - xl
        }
    } else if ax < K(3.725290298461914e-09) {
        ret 1.0 + x + xl
    }
    let r = hi - lo
    let t = r * r
    let c = r - t * (K(1.66666666666666019037e-01) + t * (K(-2.77777777770155933842e-03) + t * (K(6.61375632143793436117e-05) + t * (K(-1.65339022054652515390e-06) + t * K(4.13813679705723846039e-08)))))
    if k == 0 {
        ret 1.0 - ((r * c) / (c - 2.0) - r)
    }
    let y = 1.0 - ((lo - (r * c) / (2.0 - c)) - hi)
    ret _scale(y, k)
}

fn exp(x: float) -> float {
    if x != x {
        ret x
    }
    if x > K(7.09782712893383973096e+02) {
        ret 1.0 / 0.0
    }
    if x < K(-7.45133219101941108420e+02) {
        ret 0.0
    }
    ret _expk(x, 0.0)
}

// ---- log, log10, log2 ----

fn log(x: float) -> float {
    if x != x || x == 1.0 / 0.0 {
        ret x
    }
    if x < 0.0 {
        ret 0.0 / 0.0
    }
    if x == 0.0 {
        ret -1.0 / 0.0
    }
    var e = 0
    var m = _frexp(x, inout e)
    // the top 20 bits of the fraction, as fdlibm reads them from the high word
    let hf = int(math.floor((m - 1.0) * 1048576.0))
    if hf >= 434332 {
        m = m * 0.5
        e += 1
    }
    let f = m - 1.0
    let dk = float(e)
    if hf == 0 || hf >= 1048574 {
        if f == 0.0 {
            if e == 0 {
                ret 0.0
            }
            ret dk * K(6.93147180369123816490e-01) + dk * K(1.90821492927058770002e-10)
        }
        let r0 = f * f * (0.5 - K(0.33333333333333333) * f)
        if e == 0 {
            ret f - r0
        }
        ret dk * K(6.93147180369123816490e-01) - ((r0 - dk * K(1.90821492927058770002e-10)) - f)
    }
    let s = f / (2.0 + f)
    let z = s * s
    let w = z * z
    let t1 = w * (K(3.999999999940941908e-01) + w * (K(2.222219843214978396e-01) + w * K(1.531383769920937332e-01)))
    let t2 = z * (K(6.666666666666735130e-01) + w * (K(2.857142874366239149e-01) + w * (K(1.818357216161805012e-01) + w * K(1.479819860511658591e-01))))
    let r = t2 + t1
    if hf >= 398458 && hf <= 440401 {
        let hfsq = 0.5 * f * f
        if e == 0 {
            ret f - (hfsq - s * (hfsq + r))
        }
        ret dk * K(6.93147180369123816490e-01) - ((hfsq - (s * (hfsq + r) + dk * K(1.90821492927058770002e-10))) - f)
    }
    if e == 0 {
        ret f - s * (f - r)
    }
    ret dk * K(6.93147180369123816490e-01) - ((s * (f - r) - dk * K(1.90821492927058770002e-10)) - f)
}

// log(x) for x = 2^y * m: y and m with m in [0.5, 2) (fdlibm's log10 splits this way).
fn _logsplit(x: float, inout y: int) -> float {
    var e = 0
    let m = _frexp(x, inout e)
    if e < 0 {
        y = e + 1
        ret m * 0.5
    }
    y = e
    ret m
}

fn log10(x: float) -> float {
    if x != x || x <= 0.0 || x == 1.0 / 0.0 {
        ret log(x)
    }
    var y = 0
    let m = _logsplit(x, inout y)
    let dy = float(y)
    ret dy * K(3.69423907715893078616e-13) + K(4.34294481903251816668e-01) * log(m) + dy * K(3.01029995663611771306e-01)
}


// ---- pow: x^y = e^(y log x), with log x and the product in double-double ----

// a = hi + lo, split into two halves of 26 bits (Veltkamp), for exact products.
fn _hi26(a: float) -> float {
    let c = 134217729.0 * a
    ret c - (c - a)
}

// The rounding error of a * b (Dekker): a * b == (a * b rounded) + _prod_err(a, b) exactly.
fn _prod_err(a: float, b: float, p: float) -> float {
    let ah = _hi26(a)
    let al = a - ah
    let bh = _hi26(b)
    let bl = b - bh
    ret ((ah * bh - p) + ah * bl + al * bh) + al * bl
}

// The rounding error of a + b (Knuth's two-sum): a + b == s + _sum_err(a, b, s) exactly.
fn _sum_err(a: float, b: float, s: float) -> float {
    let bb = s - a
    ret (a - (s - bb)) + (b - bb)
}

// log(x) as hi + lo with about 2^-63 relative error, for a finite x > 0.
fn _log_dd(x: float, inout lo: float) -> float {
    var e = 0
    var m = _frexp(x, inout e)
    if m > K(1.4142135623730951) {
        m = m * 0.5
        e += 1
    }
    // s = (m - 1) / (m + 1) as sh + sl; m - 1 is exact, m + 1 is den + denl
    let num = m - 1.0
    let den = m + 1.0
    let bb = den - m
    let denl = (m - (den - bb)) + (1.0 - bb)
    let sh = num / den
    let p = sh * den
    let sl = ((num - p - _prod_err(sh, den, p)) - sh * denl) / den
    // log m = 2s + 2s^3/3 + s^5 * (2/5 + 2s^2/7 + ...)
    let z = sh * sh
    let tail = z * z * sh * (K(0.4) + z * (K(0.2857142857142857) + z * (K(0.2222222222222222) + z * (K(0.18181818181818182) + z * (K(0.15384615384615385) + z * (K(0.13333333333333333) + z * (K(0.11764705882352941) + z * (K(0.10526315789473684) + z * (K(0.09523809523809523) + z * (K(0.08695652173913043) + z * K(0.08)))))))))))
    // 2s^3/3 as c3 + c3l
    let s2 = sh * sh
    let s2l = _prod_err(sh, sh, s2) + 2.0 * sh * sl
    let s3 = s2 * sh
    let s3l = _prod_err(s2, sh, s3) + s2l * sh + s2 * sl
    let c3 = s3 * K(0.6666666666666666)
    let c3l = _prod_err(s3, K(0.6666666666666666), c3) + s3 * K(3.700743415417188e-17) + s3l * K(0.6666666666666666)
    // n ln 2 + 2s + c3 + tail, summed small to large
    let de = float(e)
    let a = de * K(6.93147180369123816490e-01)
    let al = de * K(1.90821492927058770002e-10)
    let small = tail + c3l + 2.0 * sl + al
    let t1 = c3 + small
    let t1l = _sum_err(c3, small, t1)
    let t2 = 2.0 * sh + t1
    let t2l = _sum_err(2.0 * sh, t1, t2) + t1l
    let hi = a + t2
    lo = _sum_err(a, t2, hi) + t2l
    ret hi
}

// log2 x = e + log(m) / ln 2, with log(m) and the product in double-double.
fn log2(x: float) -> float {
    if x != x || x <= 0.0 || x == 1.0 / 0.0 {
        ret log(x)
    }
    var e = 0
    var m = _frexp(x, inout e)
    if m > K(1.4142135623730951) {
        m = m * 0.5
        e += 1
    }
    var ll = 0.0
    let lh = _log_dd(m, inout ll)
    let p = lh * K(1.4426950408889634)
    let pl = _prod_err(lh, K(1.4426950408889634), p) + lh * K(2.0355273740931033e-17) + ll * K(1.4426950408889634)
    let de = float(e)
    let sum = de + p
    ret sum + (_sum_err(de, p, sum) + pl)
}

// y is an integer: 1 odd, 2 even; 0 not an integer.
fn _int_kind(y: float) -> int {
    let ay = _fabs(y)
    if ay >= 9007199254740992.0 {
        ret 2
    }
    if math.floor(ay) != ay {
        ret 0
    }
    if math.floor(ay * 0.5) * 2.0 == ay {
        ret 2
    }
    ret 1
}

fn pow(x: float, y: float) -> float {
    if y == 0.0 || x == 1.0 {
        ret 1.0
    }
    if x != x || y != y {
        ret x + y
    }
    let ax = _fabs(x)
    let yk = _int_kind(y)
    let inf = 1.0 / 0.0
    if y == inf || y == -inf {
        if ax == 1.0 {
            ret 1.0
        }
        if (ax > 1.0) == (y > 0.0) {
            ret inf
        }
        ret 0.0
    }
    if ax == 0.0 || ax == inf {
        // 0 or infinity: the reciprocal for a negative y, the sign of x for an odd y
        var z = ax
        if y < 0.0 {
            z = 1.0 / z
        }
        if _neg(x) && yk == 1 {
            ret -z
        }
        ret z
    }
    if x < 0.0 && yk == 0 {
        ret 0.0 / 0.0
    }
    let neg = x < 0.0 && yk == 1
    var r = 0.0
    if y == 1.0 {
        r = ax
    } else if y == 2.0 {
        r = ax * ax
    } else if y == 0.5 {
        r = math.sqrt(ax)
    } else if y == -1.0 {
        r = 1.0 / ax
    } else {
        var ll = 0.0
        let lh = _log_dd(ax, inout ll)
        let zh = y * lh
        if zh > K(709.79) {
            r = inf
        } else if zh < K(-745.2) {
            r = 0.0
        } else {
            let zl = _prod_err(y, lh, zh) + y * ll
            if zh > K(7.09782712893383973096e+02) {
                r = inf
            } else if zh < K(-7.45133219101941108420e+02) {
                r = 0.0
            } else {
                r = _expk(zh, zl)
            }
        }
    }
    if neg {
        ret -r
    }
    ret r
}

// ---- sin, cos, tan ----

fn _ksin(x: float, y: float, iy: int) -> float {
    if _fabs(x) < K(7.450580596923828e-09) {
        ret x
    }
    let z = x * x
    let v = z * x
    let r = K(8.33333333332248946124e-03) + z * (K(-1.98412698298579493134e-04) + z * (K(2.75573137070700676789e-06) + z * (K(-2.50507602534068634195e-08) + z * K(1.58969099521155010221e-10))))
    if iy == 0 {
        ret x + v * (K(-1.66666666666666324348e-01) + z * r)
    }
    ret x - ((z * (0.5 * y - v * r) - y) - v * K(-1.66666666666666324348e-01))
}

fn _kcos(x: float, y: float) -> float {
    let ax = _fabs(x)
    if ax < K(7.450580596923828e-09) {
        ret 1.0
    }
    let z = x * x
    let r = z * (K(4.16666666666666019037e-02) + z * (K(-1.38888888888741095749e-03) + z * (K(2.48015872894767294178e-05) + z * (K(-2.75573143513906633035e-07) + z * (K(2.08757232129817482790e-09) + z * K(-1.13596475577881948265e-11))))))
    if ax < K(0.2999999523162842) {
        ret 1.0 - (0.5 * z - (z * r - x * y))
    }
    var qx = K(0.28125)
    if ax < K(0.7812504768371582) {
        // x/4 cut to the top 21 bits of its significand (fdlibm zeroes the low word)
        let t = ax * 0.25
        if t < 0.125 {
            qx = math.floor(t * 16777216.0) / 16777216.0
        } else {
            qx = math.floor(t * 8388608.0) / 8388608.0
        }
    }
    let hz = 0.5 * z - qx
    let a = 1.0 - qx
    ret a - (hz - (z * r - x * y))
}

// The binary exponent of x (0 counts as below every other number).
fn _expo(x: float) -> int {
    if x == 0.0 {
        ret -2000
    }
    var e = 0
    let m = _frexp(_fabs(x), inout e)
    ret e
}

// x - n * pi/2 as y0 + y1, and n modulo 4 (negative for a negative x).
fn _rem_pio2(x: float, inout y0: float, inout y1: float) -> int {
    let ax = _fabs(x)
    if ax < K(0.7853984832763672) {
        y0 = x
        y1 = 0.0
        ret 0
    }
    // n * pi/2 in three parts (each exact times an n below 2^20), subtracted step by step
    // (exact below 2^19 * pi/2; less precise above, but the same on every backend)
    let nf = math.floor(ax * K(6.36619772367581382433e-01) + 0.5)
    let n = int(nf - 4.0 * math.floor(nf * 0.25))
    var r = ax - nf * K(1.57079632673412561417e+00)
    var w = nf * K(6.07710050650619224932e-11)
    y0 = r - w
    // more parts of pi/2 only when the first difference cancelled many bits
    let j = _expo(ax)
    if j - _expo(y0) > 16 {
        var t = r
        w = nf * K(6.07710050630396597660e-11)
        r = t - w
        w = nf * K(2.02226624879595063154e-21) - ((t - r) - w)
        y0 = r - w
        if j - _expo(y0) > 49 {
            t = r
            w = nf * K(2.02226624871116645580e-21)
            r = t - w
            w = nf * K(8.47842766036889956997e-32) - ((t - r) - w)
            y0 = r - w
        }
    }
    y1 = (r - y0) - w
    if x < 0.0 {
        y0 = -y0
        y1 = -y1
        ret -n
    }
    ret n
}

fn sin(x: float) -> float {
    if x != x || x == 1.0 / 0.0 || x == -1.0 / 0.0 {
        ret 0.0 / 0.0
    }
    if _fabs(x) < K(0.7853984832763672) {
        ret _ksin(x, 0.0, 0)
    }
    var y0 = 0.0
    var y1 = 0.0
    let n = _rem_pio2(x, inout y0, inout y1)
    let q = ((n % 4) + 4) % 4
    if q == 0 {
        ret _ksin(y0, y1, 1)
    }
    if q == 1 {
        ret _kcos(y0, y1)
    }
    if q == 2 {
        ret -_ksin(y0, y1, 1)
    }
    ret -_kcos(y0, y1)
}

fn cos(x: float) -> float {
    if x != x || x == 1.0 / 0.0 || x == -1.0 / 0.0 {
        ret 0.0 / 0.0
    }
    var y0 = 0.0
    var y1 = 0.0
    let n = _rem_pio2(x, inout y0, inout y1)
    let q = ((n % 4) + 4) % 4
    if q == 0 {
        ret _kcos(y0, y1)
    }
    if q == 1 {
        ret -_ksin(y0, y1, 1)
    }
    if q == 2 {
        ret -_kcos(y0, y1)
    }
    ret _ksin(y0, y1, 1)
}

// tan(x + y) (iy 1) or -1/tan(x + y) (iy -1), for |x| <= pi/4.
fn _ktan(x0: float, y0: float, iy: int) -> float {
    var x = x0
    var y = y0
    let ax = _fabs(x)
    if ax < K(3.725290298461914e-09) {
        if x == 0.0 && iy == -1 {
            ret 1.0 / ax
        }
        if iy == 1 {
            ret x
        }
        let w0 = x + y
        let z0 = _cut(w0)
        let v0 = y - (z0 - x)
        let a0 = -1.0 / w0
        let t0 = _cut(a0)
        let s0 = 1.0 + t0 * z0
        ret t0 + a0 * (s0 + t0 * v0)
    }
    let big = ax >= K(0.6743354797363281)
    let negx = x < 0.0
    if big {
        if negx {
            x = -x
            y = -y
        }
        let z1 = K(7.85398163397448278999e-01) - x
        let w1 = K(3.06161699786838301793e-17) - y
        x = z1 + w1
        y = 0.0
    }
    let z = x * x
    let w = z * z
    var r = K(1.33333333333201242699e-01) + w * (K(2.18694882948595424599e-02) + w * (K(3.59207910759131235356e-03) + w * (K(5.88041240820264096874e-04) + w * (K(7.81794442939557092300e-05) + w * K(-1.85586374855275456654e-05)))))
    let v = z * (K(5.39682539762260521377e-02) + w * (K(8.86323982359930005737e-03) + w * (K(1.45620945432529025516e-03) + w * (K(2.46463134818469906812e-04) + w * (K(7.14072491382608190305e-05) + w * K(2.59073051863633712884e-05))))))
    let s = z * x
    r = y + z * (s * (r + v) + y)
    r += K(3.33333333333334091986e-01) * s
    let ww = x + r
    if big {
        let fv = float(iy)
        let sign = if negx { -1.0 } else { 1.0 }
        ret sign * (fv - 2.0 * (x - (ww * ww / (ww + fv) - r)))
    }
    if iy == 1 {
        ret ww
    }
    let z2 = _cut(ww)
    let v2 = r - (z2 - x)
    let a2 = -1.0 / ww
    let t2 = _cut(a2)
    let s2 = 1.0 + t2 * z2
    ret t2 + a2 * (s2 + t2 * v2)
}

fn tan(x: float) -> float {
    if x != x || x == 1.0 / 0.0 || x == -1.0 / 0.0 {
        ret 0.0 / 0.0
    }
    var y0 = 0.0
    var y1 = 0.0
    let n = _rem_pio2(x, inout y0, inout y1)
    if n % 2 == 0 {
        ret _ktan(y0, y1, 1)
    }
    ret _ktan(y0, y1, -1)
}

// ---- atan, atan2, asin, acos ----

fn atan(x: float) -> float {
    if x != x {
        ret x
    }
    let ax = _fabs(x)
    if ax >= K(7.378697629483821e+19) {
        if x < 0.0 {
            ret -K(1.57079632679489655800e+00) - K(6.12323399573676603587e-17)
        }
        ret K(1.57079632679489655800e+00) + K(6.12323399573676603587e-17)
    }
    var id = -1
    var v = x
    if ax < 0.4375 {
        if ax < K(1.862645149230957e-09) {
            ret x
        }
    } else if ax < 1.1875 {
        if ax < 0.6875 {
            id = 0
            v = (2.0 * ax - 1.0) / (2.0 + ax)
        } else {
            id = 1
            v = (ax - 1.0) / (ax + 1.0)
        }
    } else if ax < 2.4375 {
        id = 2
        v = (ax - 1.5) / (1.0 + 1.5 * ax)
    } else {
        id = 3
        v = -1.0 / ax
    }
    let z = v * v
    let w = z * z
    let s1 = z * (K(3.33333333333329318027e-01) + w * (K(1.42857142725034663711e-01) + w * (K(9.09088713343650656196e-02) + w * (K(6.66107313738753120669e-02) + w * (K(4.97687799461593236017e-02) + w * K(1.62858201153657823623e-02))))))
    let s2 = w * (K(-1.99999999998764832476e-01) + w * (K(-1.11111104054623557880e-01) + w * (K(-7.69187620504482999495e-02) + w * (K(-5.83357013379057348645e-02) + w * K(-3.65315727442169155270e-02)))))
    if id < 0 {
        ret v - v * (s1 + s2)
    }
    var hi = K(1.57079632679489655800e+00)
    var lo = K(6.12323399573676603587e-17)
    if id == 0 {
        hi = K(4.63647609000806093515e-01)
        lo = K(2.26987774529616870924e-17)
    } else if id == 1 {
        hi = K(7.85398163397448278999e-01)
        lo = K(3.06161699786838301793e-17)
    } else if id == 2 {
        hi = K(9.82793723247329054082e-01)
        lo = K(1.39033110312309984516e-17)
    }
    let r = hi - ((v * (s1 + s2) - lo) - v)
    if x < 0.0 {
        ret -r
    }
    ret r
}

fn atan2(y: float, x: float) -> float {
    if x != x || y != y {
        ret x + y
    }
    if x == 1.0 {
        ret atan(y)
    }
    let pi = K(3.14159265358979311600e+00)
    let pi_lo = K(1.2246467991473531772e-16)
    let half_pi = K(1.57079632679489655800e+00)
    let tiny = K(1.0e-300)
    let inf = 1.0 / 0.0
    // which quadrant: the signs of y and x (-0.0 counts as negative)
    let m = (if _neg(y) { 1 } else { 0 }) + (if _neg(x) { 2 } else { 0 })
    if y == 0.0 {
        if m < 2 {
            ret y
        }
        if m == 2 {
            ret pi + tiny
        }
        ret -pi - tiny
    }
    if x == 0.0 {
        if y < 0.0 {
            ret -half_pi - tiny
        }
        ret half_pi + tiny
    }
    if x == inf || x == -inf {
        if y == inf || y == -inf {
            let q = K(7.8539816339744827900e-01)
            if m == 0 {
                ret q + tiny
            }
            if m == 1 {
                ret -q - tiny
            }
            if m == 2 {
                ret 3.0 * q + tiny
            }
            ret -3.0 * q - tiny
        }
        if m == 0 {
            ret 0.0
        }
        if m == 1 {
            ret -0.0
        }
        if m == 2 {
            ret pi + tiny
        }
        ret -pi - tiny
    }
    if y == inf || y == -inf {
        if y < 0.0 {
            ret -half_pi - tiny
        }
        ret half_pi + tiny
    }
    var ey = 0
    var ex = 0
    let my = _frexp(_fabs(y), inout ey)
    let mx = _frexp(_fabs(x), inout ex)
    let k = ey - ex
    var z = 0.0
    if k > 60 {
        z = half_pi + 0.5 * pi_lo
    } else if m >= 2 && k < -60 {
        z = 0.0
    } else {
        z = atan(_fabs(y / x))
    }
    if m == 0 {
        ret z
    }
    if m == 1 {
        ret -z
    }
    if m == 2 {
        ret pi - (z - pi_lo)
    }
    ret (z - pi_lo) - pi
}

// The rational approximation fdlibm's asin and acos share: p(z) / q(z).
fn _asin_p(z: float) -> float = z * (K(1.66666666666666657415e-01) + z * (K(-3.25565818622400915405e-01) + z * (K(2.01212532134862925881e-01) + z * (K(-4.00555345006794114027e-02) + z * (K(7.91534994289814532176e-04) + z * K(3.47933107596021167570e-05))))))

fn _asin_q(z: float) -> float = 1.0 + z * (K(-2.40339491173441421878e+00) + z * (K(2.02094576023350569471e+00) + z * (K(-6.88283971605453293030e-01) + z * K(7.70381505559019352791e-02))))

fn asin(x: float) -> float {
    let ax = _fabs(x)
    if x != x || ax > 1.0 {
        ret 0.0 / 0.0
    }
    if ax == 1.0 {
        ret x * K(1.57079632679489655800e+00) + x * K(6.12323399573676603587e-17)
    }
    if ax < 0.5 {
        if ax < K(7.450580596923828e-09) {
            ret x
        }
        let t = x * x
        ret x + x * (_asin_p(t) / _asin_q(t))
    }
    let t = (1.0 - ax) * 0.5
    let p = _asin_p(t)
    let q = _asin_q(t)
    let s = math.sqrt(t)
    var r = 0.0
    if ax >= K(0.9749999046325684) {
        r = K(1.57079632679489655800e+00) - (2.0 * (s + s * (p / q)) - K(6.12323399573676603587e-17))
    } else {
        let w = _cut(s)
        let c = (t - w * w) / (s + w)
        let pp = 2.0 * s * (p / q) - (K(6.12323399573676603587e-17) - 2.0 * c)
        let qq = K(7.85398163397448278999e-01) - 2.0 * w
        r = K(7.85398163397448278999e-01) - (pp - qq)
    }
    if x < 0.0 {
        ret -r
    }
    ret r
}

fn acos(x: float) -> float {
    let ax = _fabs(x)
    if x != x || ax > 1.0 {
        ret 0.0 / 0.0
    }
    if ax == 1.0 {
        if x > 0.0 {
            ret 0.0
        }
        ret K(3.14159265358979311600e+00) + 2.0 * K(6.12323399573676603587e-17)
    }
    if ax < 0.5 {
        if ax <= K(6.938893903907228e-18) {
            ret K(1.57079632679489655800e+00) + K(6.12323399573676603587e-17)
        }
        let z = x * x
        let r = _asin_p(z) / _asin_q(z)
        ret K(1.57079632679489655800e+00) - (x - (K(6.12323399573676603587e-17) - x * r))
    }
    if x < 0.0 {
        let z = (1.0 + x) * 0.5
        let s = math.sqrt(z)
        let w = (_asin_p(z) / _asin_q(z)) * s - K(6.12323399573676603587e-17)
        ret K(3.14159265358979311600e+00) - 2.0 * (s + w)
    }
    let z = (1.0 - x) * 0.5
    let s = math.sqrt(z)
    let df = _cut(s)
    let c = (z - df * df) / (s + df)
    let w = (_asin_p(z) / _asin_q(z)) * s + c
    ret 2.0 * (df + w)
}
'''

src = SRC.replace('@POW2POS@', pow2_pos).replace('@POW2NEG@', pow2_neg).replace('@SPLITUP@', split_up).replace('@SPLITDOWN@', split_down)
src = re.sub(r'K\(([-+0-9.eE]+)\)', K, src)
assert 'K(' not in src, 'unconverted constant'
open(OUT, 'w', encoding='utf-8', newline='').write(src)
print('written', len(src))
