// generated by nyra
#include <stdarg.h>
#include <float.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static const char *const nyrt_file = @FILE@;

static void nyrt_print_int(int64_t x) { printf("%lld\n", (long long)x); }
static void nyrt_print_bool(bool x) { puts(x ? "true" : "false"); }
static void nyrt_print_str(const char *x) { puts(x); }
// Formats a float exactly like JavaScript's String(x): the shortest digits that
// round-trip, laid out by the ECMAScript Number::toString rules. buf needs 32 bytes.
static char *nyrt_float_fmt(char *buf, double x) {
    if (x != x) { strcpy(buf, "NaN"); return buf; }
    if (x == 0) { strcpy(buf, "0"); return buf; }
    if (x > DBL_MAX) { strcpy(buf, "Infinity"); return buf; }
    if (x < -DBL_MAX) { strcpy(buf, "-Infinity"); return buf; }
    char *out = buf;
    if (x < 0) { *out++ = '-'; x = -x; }
    char tmp[40];
    for (int p = 1; p <= 17; p++) {
        snprintf(tmp, sizeof tmp, "%.*e", p - 1, x);
        if (strtod(tmp, NULL) == x) break;
    }
    char digits[20];
    int k = 0;
    char *s = tmp;
    for (; *s && *s != 'e'; s++) if (*s >= '0' && *s <= '9') digits[k++] = *s;
    while (k > 1 && digits[k - 1] == '0') k--;
    int n = atoi(s + 1) + 1; // the value is 0.DIGITS * 10^n
    if (k <= n && n <= 21) {
        memcpy(out, digits, k); out += k;
        for (int i = k; i < n; i++) *out++ = '0';
    } else if (0 < n && n <= 21) {
        memcpy(out, digits, n); out += n; *out++ = '.';
        memcpy(out, digits + n, k - n); out += k - n;
    } else if (-6 < n && n <= 0) {
        *out++ = '0'; *out++ = '.';
        for (int i = n; i < 0; i++) *out++ = '0';
        memcpy(out, digits, k); out += k;
    } else {
        *out++ = digits[0];
        if (k > 1) { *out++ = '.'; memcpy(out, digits + 1, k - 1); out += k - 1; }
        out += sprintf(out, "e%c%d", n > 0 ? '+' : '-', n > 0 ? n - 1 : 1 - n);
    }
    *out = '\0';
    return buf;
}
static void nyrt_print_float(double x) { char buf[32]; puts(nyrt_float_fmt(buf, x)); }
// Runtime errors: flush stdout, report like a compile error (or as JSON when
// NYRA_JSON is set) on stderr, exit with code 101. Same text as the JS backend.
static void nyrt_json_str(const char *s) {
    fputc('"', stderr);
    for (; *s; s++) {
        unsigned char c = (unsigned char)*s;
        if (c == '"' || c == '\\') { fputc('\\', stderr); fputc(c, stderr); }
        else if (c == '\n') fputs("\\n", stderr);
        else if (c == '\r') fputs("\\r", stderr);
        else if (c == '\t') fputs("\\t", stderr);
        else if (c == '\b') fputs("\\b", stderr);
        else if (c == '\f') fputs("\\f", stderr);
        else if (c < 0x20) fprintf(stderr, "\\u%04x", c);
        else fputc(c, stderr);
    }
    fputc('"', stderr);
}
static void nyrt_panic(const char *code, const char *msg, const char *hint, int line, int col) {
    fflush(stdout);
    if (getenv("NYRA_JSON")) {
        fprintf(stderr, "{\"ok\":false,\"errors\":[{\"code\":\"%s\",\"message\":", code);
        nyrt_json_str(msg);
        fputs(",\"file\":", stderr);
        nyrt_json_str(nyrt_file);
        fprintf(stderr, ",\"line\":%d,\"col\":%d,\"hint\":", line, col);
        nyrt_json_str(hint);
        fputs(",\"runtime\":true}]}\n", stderr);
    } else {
        fprintf(stderr, "runtime error[%s]: %s\n  --> %s:%d:%d\n  = hint: %s\n", code, msg, nyrt_file, line, col, hint);
    }
    exit(101);
}
// int / and %: division by zero is a runtime error; MIN / -1 wraps (x86 would trap).
static int64_t nyrt_div(int64_t a, int64_t b, int line, int col) {
    if (b == 0) nyrt_panic("E0241", "division by zero", "check the divisor first", line, col);
    if (b == -1) return (int64_t)(0 - (uint64_t)a);
    return a / b;
}
static int64_t nyrt_mod(int64_t a, int64_t b, int line, int col) {
    if (b == 0) nyrt_panic("E0241", "division by zero", "check the divisor first", line, col);
    if (b == -1) return 0;
    return a % b;
}
// int(x) of a float: truncates toward zero; NaN or a value outside the int range is an error.
static int64_t nyrt_f2i(double x, int line, int col) {
    if (x != x || x >= 9223372036854775807.0 || x < -9223372036854775808.0) {
        char num[32], msg[64];
        snprintf(msg, sizeof msg, "cannot convert %s to int", nyrt_float_fmt(num, x));
        nyrt_panic("E0245", msg, "int(x) needs a float that is not NaN and fits in an int", line, col);
    }
    return (int64_t)x;
}
// Builds an interpolated string. Not freed yet (the v0.3 memory model will).
static const char *nyrt_fmt(const char *fmt, ...) {
    va_list ap;
    va_start(ap, fmt);
    int n = vsnprintf(NULL, 0, fmt, ap);
    va_end(ap);
    char *s = malloc((size_t)n + 1);
    if (!s) { fputs("nyra: out of memory\n", stderr); exit(1); }
    va_start(ap, fmt);
    vsnprintf(s, (size_t)n + 1, fmt, ap);
    va_end(ap);
    return s;
}

