// generated by nyra
#include <float.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// Branch hints and cold paths: the fast path of an index check or a write stays small enough to
// inline, and the error paths move out of the hot loops.
#if defined(__GNUC__) || defined(__clang__)
#define NYRT_UNLIKELY(x) __builtin_expect(!!(x), 0)
#define NYRT_COLD __attribute__((noinline, cold))
#define NYRT_NORETURN __attribute__((noinline, cold, noreturn))
#else
#define NYRT_UNLIKELY(x) (x)
#define NYRT_COLD
#define NYRT_NORETURN
#endif

static const char *const nyrt_file = @FILE@;

// Formats a float exactly like JavaScript's String(x): the shortest digits that
// round-trip, laid out by the ECMAScript Number::toString rules. buf needs 32 bytes.
static char *nyrt_float_fmt(char *buf, double x) {
    if (x != x) { strcpy(buf, "NaN"); return buf; }
    if (x == 0) { strcpy(buf, "0"); return buf; }
    if (x > DBL_MAX) { strcpy(buf, "Infinity"); return buf; }
    if (x < -DBL_MAX) { strcpy(buf, "-Infinity"); return buf; }
    char *out = buf;
    if (x < 0) { *out++ = '-'; x = -x; }
    char tmp[40];
    for (int p = 1; p <= 17; p++) {
        snprintf(tmp, sizeof tmp, "%.*e", p - 1, x);
        if (strtod(tmp, NULL) == x) break;
    }
    char digits[20];
    int k = 0;
    char *s = tmp;
    for (; *s && *s != 'e'; s++) if (*s >= '0' && *s <= '9') digits[k++] = *s;
    while (k > 1 && digits[k - 1] == '0') k--;
    int n = atoi(s + 1) + 1; // the value is 0.DIGITS * 10^n
    if (k <= n && n <= 21) {
        memcpy(out, digits, k); out += k;
        for (int i = k; i < n; i++) *out++ = '0';
    } else if (0 < n && n <= 21) {
        memcpy(out, digits, n); out += n; *out++ = '.';
        memcpy(out, digits + n, k - n); out += k - n;
    } else if (-6 < n && n <= 0) {
        *out++ = '0'; *out++ = '.';
        for (int i = n; i < 0; i++) *out++ = '0';
        memcpy(out, digits, k); out += k;
    } else {
        *out++ = digits[0];
        if (k > 1) { *out++ = '.'; memcpy(out, digits + 1, k - 1); out += k - 1; }
        out += sprintf(out, "e%c%d", n > 0 ? '+' : '-', n > 0 ? n - 1 : 1 - n);
    }
    *out = '\0';
    return buf;
}
// Runtime errors: flush stdout, report like a compile error (or as JSON when
// NYRA_JSON is set) on stderr, exit with code 101. Same text as the JS backend.
static void nyrt_json_str(const char *s) {
    fputc('"', stderr);
    for (; *s; s++) {
        unsigned char c = (unsigned char)*s;
        if (c == '"' || c == '\\') { fputc('\\', stderr); fputc(c, stderr); }
        else if (c == '\n') fputs("\\n", stderr);
        else if (c == '\r') fputs("\\r", stderr);
        else if (c == '\t') fputs("\\t", stderr);
        else if (c == '\b') fputs("\\b", stderr);
        else if (c == '\f') fputs("\\f", stderr);
        else if (c < 0x20) fprintf(stderr, "\\u%04x", c);
        else fputc(c, stderr);
    }
    fputc('"', stderr);
}
static NYRT_NORETURN void nyrt_panic(const char *code, const char *msg, const char *hint, int line, int col) {
    fflush(stdout);
    if (getenv("NYRA_JSON")) {
        fprintf(stderr, "{\"ok\":false,\"errors\":[{\"code\":\"%s\",\"message\":", code);
        nyrt_json_str(msg);
        fputs(",\"file\":", stderr);
        nyrt_json_str(nyrt_file);
        fprintf(stderr, ",\"line\":%d,\"col\":%d,\"hint\":", line, col);
        nyrt_json_str(hint);
        fputs(",\"runtime\":true}]}\n", stderr);
    } else {
        fprintf(stderr, "runtime error[%s]: %s\n  --> %s:%d:%d\n  = hint: %s\n  = explain: nyra explain %s\n", code, msg, nyrt_file,
                line, col, hint, code);
    }
    exit(101);
}
// int + - * / and negation: a result outside the 64-bit range is a runtime error (E0255).
// The error path is out of line and takes few arguments (the operands and one packed position:
// line, column and operator). A call with more made the C compiler give up inlining and
// unrolling around the checked operations (`fib` ran 2.5 times slower than without checks).
#define NYRT_AT(line, col, op) (((int64_t)(line) << 32) | ((int64_t)((col) & 0xffffff) << 8) | (int64_t)(op))
static NYRT_NORETURN void nyrt_overflow(int64_t a, int64_t b, int64_t at) {
    char msg[128], op[2] = { (char)(at & 0xff), 0 };
    int line = (int)(at >> 32), col = (int)((at >> 8) & 0xffffff);
    if (*op == '~') snprintf(msg, sizeof msg, "int overflow: -(%lld) does not fit in 64 bits", (long long)a);
    else snprintf(msg, sizeof msg, "int overflow: %lld %s %lld does not fit in 64 bits", (long long)a, op, (long long)b);
    nyrt_panic("E0255", msg,
               "an int holds -9223372036854775808 to 9223372036854775807: use smaller values, or keep a running value small with `%` (e.g. `h = (h * 31 + x) % 1000000007`)",
               line, col);
}
#if defined(__has_builtin)
#if __has_builtin(__builtin_add_overflow) && __has_builtin(__builtin_mul_overflow)
#define NYRT_OVF_BUILTINS 1
#endif
#elif defined(__GNUC__) && __GNUC__ >= 5 && !defined(__TINYC__)
#define NYRT_OVF_BUILTINS 1
#endif
static inline int64_t nyrt_add(int64_t a, int64_t b, int line, int col) {
#ifdef NYRT_OVF_BUILTINS
    int64_t r;
    if (NYRT_UNLIKELY(__builtin_add_overflow(a, b, &r))) nyrt_overflow(a, b, NYRT_AT(line, col, '+'));
    return r;
#else
    if ((b > 0 && a > INT64_MAX - b) || (b < 0 && a < INT64_MIN - b)) nyrt_overflow(a, b, NYRT_AT(line, col, '+'));
    return a + b;
#endif
}
static inline int64_t nyrt_sub(int64_t a, int64_t b, int line, int col) {
#ifdef NYRT_OVF_BUILTINS
    int64_t r;
    if (NYRT_UNLIKELY(__builtin_sub_overflow(a, b, &r))) nyrt_overflow(a, b, NYRT_AT(line, col, '-'));
    return r;
#else
    if ((b < 0 && a > INT64_MAX + b) || (b > 0 && a < INT64_MIN + b)) nyrt_overflow(a, b, NYRT_AT(line, col, '-'));
    return a - b;
#endif
}
static inline int64_t nyrt_mul(int64_t a, int64_t b, int line, int col) {
#ifdef NYRT_OVF_BUILTINS
    int64_t r;
    if (NYRT_UNLIKELY(__builtin_mul_overflow(a, b, &r))) nyrt_overflow(a, b, NYRT_AT(line, col, '*'));
    return r;
#else
    if (a > 0 ? (b > 0 ? a > INT64_MAX / b : b < INT64_MIN / a) : (b > 0 ? a < INT64_MIN / b : (a != 0 && b < INT64_MAX / a)))
        nyrt_overflow(a, b, NYRT_AT(line, col, '*'));
    return a * b;
#endif
}
static inline int64_t nyrt_neg(int64_t a, int line, int col) {
    if (NYRT_UNLIKELY(a == INT64_MIN)) nyrt_overflow(a, 0, NYRT_AT(line, col, '~'));
    return -a;
}
// int / and %: division by zero is a runtime error; MIN / -1 overflows (x86 would trap).
static NYRT_NORETURN void nyrt_div_zero(int line, int col) {
    nyrt_panic("E0241", "division by zero", "check the divisor first", line, col);
}
static inline int64_t nyrt_div(int64_t a, int64_t b, int line, int col) {
    if (NYRT_UNLIKELY(b == 0)) nyrt_div_zero(line, col);
    if (NYRT_UNLIKELY(b == -1)) {
        if (a == INT64_MIN) nyrt_overflow(a, b, NYRT_AT(line, col, '/'));
        return -a;
    }
    return a / b;
}
static inline int64_t nyrt_mod(int64_t a, int64_t b, int line, int col) {
    if (NYRT_UNLIKELY(b == 0)) nyrt_div_zero(line, col);
    if (NYRT_UNLIKELY(b == -1)) return 0;
    return a % b;
}
// `for i in a..b step k`: a step of 0 would never end.
static void nyrt_check_step(int64_t k, int line, int col) {
    if (k == 0) nyrt_panic("E0243", "range step must not be 0", "use a positive step to count up and a negative one to count down", line, col);
}
// `opt.unwrap()` of `none`.
static void nyrt_check_some(bool has, int line, int col) {
    if (!has) nyrt_panic("E0350", "unwrap() of none", "check `x != none` first, or give a default with `x ?? value`", line, col);
}
// `xs.min()` / `xs.max()` of an empty array (`n` elements seen; `max` says which method).
static void nyrt_check_non_empty(int64_t n, int64_t max, int line, int col) {
    if (n == 0) {
        nyrt_panic("E0247", max ? "max() of an empty array" : "min() of an empty array",
                   "an empty array has no smallest or largest element: check `xs.len() > 0` first, or start from a value of your own with `fold`", line, col);
    }
}
// int(x) of a float: truncates toward zero; NaN or a value outside the int range is an error.
static int64_t nyrt_f2i(double x, int line, int col) {
    if (x != x || x >= 9223372036854775807.0 || x < -9223372036854775808.0) {
        char num[32], msg[64];
        snprintf(msg, sizeof msg, "cannot convert %s to int", nyrt_float_fmt(num, x));
        nyrt_panic("E0245", msg, "int(x) needs a float that is not NaN and fits in an int", line, col);
    }
    return (int64_t)x;
}
